### ISSUE TITLE
Execute rocket_chat_notify:starting cap aborted! Errno::ECONNRESET: Connection reset by peer - SSL_connect

### ISSUE THREAD

**Issue by medesko** [cbajohr/capistrano-rocket-chat#5]
Any idea for this Error ? 

Thank you for your help!

** Execute rocket_chat_notify:starting cap aborted! Errno::ECONNRESET: Connection reset by peer - SSL_connect

My opensll version : OpenSSL 1.0.2l  25 May 2017
ruby 2.4.1p111  

`** Execute rocket_chat_notify:failed
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect': Connection reset by peer - SSL_connect (Errno::ECONNRESET)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `block in connect'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1373:in `request'
        from /Library/Ruby/Gems/2.0.0/gems/httparty-0.13.7/lib/httparty/request.rb:117:in `perform'
        from /Library/Ruby/Gems/2.0.0/gems/httparty-0.13.7/lib/httparty.rb:545:in `perform_request'
        from /Library/Ruby/Gems/2.0.0/gems/httparty-0.13.7/lib/httparty.rb:492:in `post'
        from /Library/Ruby/Gems/2.0.0/gems/httparty-0.13.7/lib/httparty.rb:587:in `post'
        from /Library/Ruby/Gems/2.0.0/gems/capistrano-rocket-chat-0.1.7/lib/capistrano/tasks/rocket_chat.cap:61:in `notify'
        from /Library/Ruby/Gems/2.0.0/gems/capistrano-rocket-chat-0.1.7/lib/capistrano/tasks/rocket_chat.cap:21:in `block (3 levels) in <top (required)>'
        from /Library/Ruby/Gems/2.0.0/gems/sshkit-1.11.5/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
        from /Library/Ruby/Gems/2.0.0/gems/sshkit-1.11.5/lib/sshkit/backends/abstract.rb:29:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/sshkit-1.11.5/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
`

**Comment by cbajohr** [comment]
Seems like your rocket chat url is wrong, or not set.

Did you set your rocket chat url including the webhook token in your deploy.rb?

`set :rocket_chat_webhook_url, "https://mychat.com/hooks/MYTOKEN"`

**Comment by medesko** [comment]
Yes @cbajohr  I have already set the url

**Comment by cbajohr** [comment]
It is extremely hard to see the exact problem from here. 
All I can say is, that it has to be a problem with the connection from your app to your rocket chat host.
You should check on that. 
May be you could try a shell curl call from the same machine first.

**Comment by medesko** [comment]
@cbajohr thank u, my problem is solved. it from my tls version.
